import { z } from "zod";

export const dutyScheduleSchema = z
  .object({
    pharmacyId: z.coerce.number().int().positive(),
    startsAt: z.string().datetime(),
    endsAt: z.string().datetime(),
    mode: z.enum(["manual", "automatic"]),
    status: z.enum(["draft", "published", "closed"]).default("draft"),
    notes: z.string().max(500).optional()
  })
  .refine((value) => new Date(value.endsAt).getTime() > new Date(value.startsAt).getTime(), {
    message: "Data final deve ser maior que data inicial",
    path: ["endsAt"]
  });

export const autoGenerateDutySchema = z.object({
  startWeek: z.string().date(),
  weeksCount: z.coerce.number().int().min(1).max(156),
  status: z.enum(["draft", "published"]).default("draft")
});

export type DutyScheduleInput = z.infer<typeof dutyScheduleSchema>;
export type AutoGenerateDutyInput = z.infer<typeof autoGenerateDutySchema>;
