import { z } from "zod";

export const dutyScheduleSchema = z
  .object({
    pharmacyId: z.coerce.number().int().positive(),
    weekStart: z.string().date(),
    status: z.enum(["draft", "published", "closed"]).default("draft"),
    notes: z
      .string()
      .trim()
      .max(500)
      .optional()
  });

export const autoGenerateDutySchema = z.object({
  startWeek: z.string().date(),
  weeksCount: z.coerce.number().int().min(1).max(156),
  status: z.enum(["draft", "published"]).default("draft")
});

export type DutyScheduleInput = z.infer<typeof dutyScheduleSchema>;
export type AutoGenerateDutyInput = z.infer<typeof autoGenerateDutySchema>;
