"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useTransition } from "react";
import { useForm } from "react-hook-form";

import { createManualDutyAction, generateAutomaticDutyCalendarAction } from "@/actions/admin/duty-actions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import {
  autoGenerateDutySchema,
  dutyScheduleSchema,
  type AutoGenerateDutyInput,
  type DutyScheduleInput
} from "@/lib/validators/duty";

export function DutyGeneratorForm() {
  const [isPending, startTransition] = useTransition();

  const manualForm = useForm<DutyScheduleInput>({
    resolver: zodResolver(dutyScheduleSchema),
    defaultValues: {
      pharmacyId: 1,
      startsAt: new Date().toISOString(),
      endsAt: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
      mode: "manual",
      status: "draft",
      notes: ""
    }
  });

  const autoForm = useForm<AutoGenerateDutyInput>({
    resolver: zodResolver(autoGenerateDutySchema),
    defaultValues: {
      startWeek: new Date().toISOString().slice(0, 10),
      weeksCount: 12,
      status: "draft"
    }
  });

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Criar plantão manual</CardTitle>
        </CardHeader>
        <CardContent>
          <form
            className="grid gap-3"
            onSubmit={manualForm.handleSubmit((values) => {
              startTransition(async () => {
                await createManualDutyAction(values);
              });
            })}
          >
            <Input type="number" placeholder="ID da farmácia" {...manualForm.register("pharmacyId")} />
            <Input type="datetime-local" {...manualForm.register("startsAt")} />
            <Input type="datetime-local" {...manualForm.register("endsAt")} />
            <Select {...manualForm.register("status")}>
              <option value="draft">Rascunho</option>
              <option value="published">Publicado</option>
              <option value="closed">Encerrado</option>
            </Select>
            <Button type="submit" disabled={isPending}>Salvar plantão manual</Button>
          </form>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Gerar calendário automático</CardTitle>
        </CardHeader>
        <CardContent>
          <form
            className="grid gap-3"
            onSubmit={autoForm.handleSubmit((values) => {
              startTransition(async () => {
                await generateAutomaticDutyCalendarAction(values);
              });
            })}
          >
            <Input type="date" {...autoForm.register("startWeek")} />
            <Input type="number" min={1} max={156} {...autoForm.register("weeksCount")} />
            <Select {...autoForm.register("status")}>
              <option value="draft">Rascunho</option>
              <option value="published">Publicado</option>
            </Select>
            <Button type="submit" variant="secondary" disabled={isPending}>
              Gerar calendário
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
