"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { endOfWeek, format, parseISO, startOfWeek } from "date-fns";
import { ptBR } from "date-fns/locale";
import { CalendarClock, CalendarRange, CheckCircle2, Sparkles } from "lucide-react";
import { useMemo, useState, useTransition } from "react";
import { useForm } from "react-hook-form";

import { createManualDutyAction, generateAutomaticDutyCalendarAction } from "@/actions/admin/duty-actions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import {
  autoGenerateDutySchema,
  dutyScheduleSchema,
  type AutoGenerateDutyInput,
  type DutyScheduleInput
} from "@/lib/validators/duty";

type PharmacyOption = {
  id: number;
  name: string;
  rotation_order: number;
};

type DutyGeneratorFormProps = {
  pharmacies: PharmacyOption[];
};

type Feedback = {
  tone: "success" | "error";
  message: string;
};

function defaultWeekStartDate() {
  const weekStart = startOfWeek(new Date(), { weekStartsOn: 1 });
  return format(weekStart, "yyyy-MM-dd");
}

function formatWeekRangeLabel(weekStart: string) {
  if (!weekStart) {
    return "Selecione uma data da semana";
  }

  try {
    const parsedDate = parseISO(weekStart);
    if (Number.isNaN(parsedDate.getTime())) {
      return "Selecione uma data válida";
    }

    const normalizedStart = startOfWeek(parsedDate, { weekStartsOn: 1 });
    const normalizedEnd = endOfWeek(normalizedStart, { weekStartsOn: 1 });

    return `${format(normalizedStart, "dd/MM/yyyy", { locale: ptBR })} até ${format(normalizedEnd, "dd/MM/yyyy", { locale: ptBR })}`;
  } catch {
    return "Selecione uma data válida";
  }
}

function FieldError({ message }: { message?: string }) {
  if (!message) {
    return null;
  }

  return <p className="text-xs font-medium text-rose-600">{message}</p>;
}

export function DutyGeneratorForm({ pharmacies }: DutyGeneratorFormProps) {
  const [isManualPending, startManualTransition] = useTransition();
  const [isAutomaticPending, startAutomaticTransition] = useTransition();
  const [manualFeedback, setManualFeedback] = useState<Feedback | null>(null);
  const [automaticFeedback, setAutomaticFeedback] = useState<Feedback | null>(null);
  const hasPharmacies = pharmacies.length > 0;

  const manualForm = useForm<DutyScheduleInput>({
    resolver: zodResolver(dutyScheduleSchema),
    defaultValues: {
      pharmacyId: pharmacies[0]?.id,
      weekStart: defaultWeekStartDate(),
      status: "draft",
      notes: ""
    }
  });

  const autoForm = useForm<AutoGenerateDutyInput>({
    resolver: zodResolver(autoGenerateDutySchema),
    defaultValues: {
      startWeek: defaultWeekStartDate(),
      weeksCount: 12,
      status: "draft"
    }
  });

  const selectedWeekStart = manualForm.watch("weekStart");
  const manualRangeLabel = useMemo(() => formatWeekRangeLabel(selectedWeekStart), [selectedWeekStart]);

  return (
    <div className="grid gap-4 xl:grid-cols-[1.2fr_1fr]">
      <Card className="border-primary/20">
        <CardHeader className="space-y-3">
          <div className="inline-flex w-fit items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-primary">
            <CalendarClock className="h-3.5 w-3.5" />
            Manual
          </div>
          <CardTitle className="text-base">Criar plantão por semana</CardTitle>
          <p className="text-sm text-muted-foreground">
            Escolha a farmácia e uma data da semana. O sistema ajusta automaticamente para segunda a domingo.
          </p>
        </CardHeader>
        <CardContent className="space-y-4">
          {!hasPharmacies ? (
            <div className="rounded-lg border border-warning/30 bg-warning/10 px-3 py-2 text-sm text-warning-foreground">
              Nenhuma farmácia ativa encontrada. Ative uma farmácia para criar plantões.
            </div>
          ) : null}

          <form
            className="space-y-4"
            onSubmit={manualForm.handleSubmit((values) => {
              setManualFeedback(null);
              startManualTransition(async () => {
                try {
                  await createManualDutyAction(values);
                  setManualFeedback({
                    tone: "success",
                    message: `Plantão salvo para ${formatWeekRangeLabel(values.weekStart)}.`
                  });
                  manualForm.setValue("notes", "");
                } catch (error) {
                  setManualFeedback({
                    tone: "error",
                    message: error instanceof Error ? error.message : "Não foi possível salvar o plantão manual."
                  });
                }
              });
            })}
          >
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-1.5">
                <label className="text-sm font-medium">Farmácia</label>
                <Select {...manualForm.register("pharmacyId")} disabled={!hasPharmacies}>
                  {hasPharmacies ? null : <option value="">Sem farmácias ativas</option>}
                  {pharmacies.map((pharmacy) => (
                    <option key={pharmacy.id} value={pharmacy.id}>
                      #{pharmacy.rotation_order} · {pharmacy.name}
                    </option>
                  ))}
                </Select>
                <FieldError message={manualForm.formState.errors.pharmacyId?.message} />
              </div>

              <div className="space-y-1.5">
                <label className="text-sm font-medium">Data de referência da semana</label>
                <Input type="date" {...manualForm.register("weekStart")} />
                <FieldError message={manualForm.formState.errors.weekStart?.message} />
              </div>
            </div>

            <div className="rounded-lg border border-primary/20 bg-primary/5 px-3 py-2">
              <p className="text-xs font-semibold uppercase tracking-wide text-primary/80">
                Período que será salvo
              </p>
              <p className="text-sm font-semibold text-foreground">{manualRangeLabel}</p>
              <p className="text-xs text-muted-foreground">Semana sempre fechada de segunda a domingo.</p>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-1.5">
                <label className="text-sm font-medium">Status</label>
                <Select {...manualForm.register("status")}>
                  <option value="draft">Rascunho</option>
                  <option value="published">Publicado</option>
                  <option value="closed">Encerrado</option>
                </Select>
                <FieldError message={manualForm.formState.errors.status?.message} />
              </div>

              <div className="space-y-1.5">
                <label className="text-sm font-medium">Observação (opcional)</label>
                <Textarea
                  rows={3}
                  className="min-h-0 resize-none"
                  placeholder="Ex.: plantão especial de feriado."
                  {...manualForm.register("notes")}
                />
                <FieldError message={manualForm.formState.errors.notes?.message} />
              </div>
            </div>

            <Button type="submit" className="w-full sm:w-auto" disabled={isManualPending || !hasPharmacies}>
              {isManualPending ? "Salvando..." : "Salvar plantão manual"}
            </Button>
          </form>

          {manualFeedback ? (
            <p
              className={
                manualFeedback.tone === "success"
                  ? "text-sm font-medium text-success"
                  : "text-sm font-medium text-rose-600"
              }
            >
              {manualFeedback.tone === "success" ? <CheckCircle2 className="mr-1 inline h-4 w-4" /> : null}
              {manualFeedback.message}
            </p>
          ) : null}
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="space-y-3">
          <div className="inline-flex w-fit items-center gap-2 rounded-full border border-border bg-muted px-3 py-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            <Sparkles className="h-3.5 w-3.5" />
            Automático
          </div>
          <CardTitle className="text-base">Gerar calendário de rodízio</CardTitle>
          <p className="text-sm text-muted-foreground">
            Usa a ordem de rodízio das farmácias ativas para gerar várias semanas de uma vez.
          </p>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="rounded-lg border border-border/80 bg-muted/40 px-3 py-2 text-sm text-muted-foreground">
            <p className="font-medium text-foreground">Farmácias ativas no rodízio: {pharmacies.length}</p>
            <p>
              {hasPharmacies
                ? `Ordem atual: ${pharmacies
                    .slice(0, 4)
                    .map((pharmacy) => pharmacy.name)
                    .join(" → ")}${pharmacies.length > 4 ? "..." : ""}`
                : "Ative ao menos uma farmácia para gerar calendário automático."}
            </p>
          </div>

          <form
            className="space-y-4"
            onSubmit={autoForm.handleSubmit((values) => {
              setAutomaticFeedback(null);
              startAutomaticTransition(async () => {
                try {
                  await generateAutomaticDutyCalendarAction(values);
                  setAutomaticFeedback({
                    tone: "success",
                    message: `Calendário gerado com ${values.weeksCount} semana(s).`
                  });
                } catch (error) {
                  setAutomaticFeedback({
                    tone: "error",
                    message: error instanceof Error ? error.message : "Não foi possível gerar o calendário automático."
                  });
                }
              });
            })}
          >
            <div className="space-y-1.5">
              <label className="text-sm font-medium">Primeira semana</label>
              <Input type="date" {...autoForm.register("startWeek")} />
              <FieldError message={autoForm.formState.errors.startWeek?.message} />
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-1.5">
                <label className="text-sm font-medium">Quantidade de semanas</label>
                <Input type="number" min={1} max={156} {...autoForm.register("weeksCount")} />
                <FieldError message={autoForm.formState.errors.weeksCount?.message} />
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-medium">Status inicial</label>
                <Select {...autoForm.register("status")}>
                  <option value="draft">Rascunho</option>
                  <option value="published">Publicado</option>
                </Select>
              </div>
            </div>

            <Button type="submit" variant="secondary" className="w-full sm:w-auto" disabled={isAutomaticPending || !hasPharmacies}>
              <CalendarRange className="h-4 w-4" />
              {isAutomaticPending ? "Gerando..." : "Gerar calendário automático"}
            </Button>
          </form>

          {automaticFeedback ? (
            <p className={automaticFeedback.tone === "success" ? "text-sm font-medium text-success" : "text-sm font-medium text-rose-600"}>
              {automaticFeedback.message}
            </p>
          ) : null}
        </CardContent>
      </Card>
    </div>
  );
}
