"use server";

import { endOfWeek, formatISO, parseISO, startOfWeek } from "date-fns";
import { revalidatePath } from "next/cache";

import { requireSuperadmin } from "@/lib/auth/guards";
import { scheduleNotification } from "@/lib/notifications/dispatcher";
import { generateRotationalDuties, reminderDateForFavoriteStart } from "@/lib/schedules/engine";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { autoGenerateDutySchema, dutyScheduleSchema } from "@/lib/validators/duty";

export async function createManualDutyAction(payload: unknown) {
  const { user } = await requireSuperadmin();
  const parsed = dutyScheduleSchema.parse(payload);
  const supabase = await createServerSupabaseClient();
  const alignedWeekStart = startOfWeek(parseISO(parsed.weekStart), { weekStartsOn: 1 });
  const alignedWeekEnd = endOfWeek(alignedWeekStart, { weekStartsOn: 1 });
  const startsAt = alignedWeekStart.toISOString();
  const endsAt = alignedWeekEnd.toISOString();
  const weekStart = formatISO(alignedWeekStart, { representation: "date" });
  const weekEnd = formatISO(alignedWeekEnd, { representation: "date" });
  const notes = parsed.notes?.trim() ? parsed.notes.trim() : null;

  const { data: createdDuty, error } = await supabase
    .from("duty_schedules")
    .insert({
      pharmacy_id: parsed.pharmacyId,
      starts_at: startsAt,
      ends_at: endsAt,
      week_start: weekStart,
      week_end: weekEnd,
      mode: "manual",
      status: parsed.status,
      notes,
      created_by: user.id
    })
    .select("id")
    .single<{ id: number }>();

  if (error || !createdDuty) {
    if (error?.code === "23P01") {
      throw new Error("Já existe um plantão cadastrado para esta semana.");
    }

    throw new Error(error?.message ?? "Falha ao criar plantão");
  }

  const { data: pharmacy } = await supabase
    .from("pharmacies")
    .select("id, name")
    .eq("id", parsed.pharmacyId)
    .single<{ id: number; name: string }>();

  if (pharmacy && parsed.status === "published") {
    await scheduleNotification({
      type: "weekly_general",
      dutyScheduleId: createdDuty.id,
      pharmacyId: pharmacy.id,
      pharmacyName: pharmacy.name,
      startsAt,
      endsAt,
      scheduledFor: startsAt,
      eventKey: `weekly_general_${createdDuty.id}`
    });

    await scheduleNotification({
      type: "favorite_reminder",
      dutyScheduleId: createdDuty.id,
      pharmacyId: pharmacy.id,
      pharmacyName: pharmacy.name,
      startsAt,
      endsAt,
      scheduledFor: reminderDateForFavoriteStart(alignedWeekStart).toISOString(),
      eventKey: `favorite_reminder_${createdDuty.id}`
    });
  }

  revalidatePath("/admin/plantoes");
  revalidatePath("/");
}

export async function generateAutomaticDutyCalendarAction(payload: unknown) {
  const { user } = await requireSuperadmin();
  const parsed = autoGenerateDutySchema.parse(payload);
  const supabase = await createServerSupabaseClient();

  const { data: pharmacies, error: pharmaciesError } = await supabase
    .from("pharmacies")
    .select("id")
    .eq("status", "active")
    .order("rotation_order", { ascending: true });

  if (pharmaciesError || !pharmacies || pharmacies.length === 0) {
    throw new Error("Não foi possível carregar farmácias ativas para rodízio");
  }

  const duties = generateRotationalDuties({
    pharmacyIdsInOrder: pharmacies.map((item: { id: number }) => item.id),
    startWeekDate: new Date(parsed.startWeek),
    weeksCount: parsed.weeksCount,
    status: parsed.status,
    mode: "automatic"
  }).map((duty) => ({
    pharmacy_id: duty.pharmacyId,
    starts_at: duty.startsAt,
    ends_at: duty.endsAt,
    week_start: duty.weekStart,
    week_end: duty.weekEnd,
    mode: duty.mode,
    status: duty.status,
    created_by: user.id
  }));

  const { error: insertError } = await supabase.from("duty_schedules").insert(duties);

  if (insertError) {
    if (insertError.code === "23P01") {
      throw new Error("Já existe plantão em parte do período informado. Ajuste a semana inicial ou remova conflitos.");
    }

    throw new Error(insertError.message);
  }

  revalidatePath("/admin/plantoes");
}
