"use server";

import { revalidatePath } from "next/cache";

import { requireSuperadmin } from "@/lib/auth/guards";
import { scheduleNotification } from "@/lib/notifications/dispatcher";
import { generateRotationalDuties, reminderDateForFavoriteStart } from "@/lib/schedules/engine";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { autoGenerateDutySchema, dutyScheduleSchema } from "@/lib/validators/duty";

export async function createManualDutyAction(payload: unknown) {
  const { user } = await requireSuperadmin();
  const parsed = dutyScheduleSchema.parse(payload);
  const supabase = await createServerSupabaseClient();

  const { data: createdDuty, error } = await supabase
    .from("duty_schedules")
    .insert({
      pharmacy_id: parsed.pharmacyId,
      starts_at: parsed.startsAt,
      ends_at: parsed.endsAt,
      week_start: parsed.startsAt,
      week_end: parsed.endsAt,
      mode: parsed.mode,
      status: parsed.status,
      notes: parsed.notes ?? null,
      created_by: user.id
    })
    .select("id")
    .single<{ id: number }>();

  if (error || !createdDuty) {
    throw new Error(error?.message ?? "Falha ao criar plantão");
  }

  const { data: pharmacy } = await supabase
    .from("pharmacies")
    .select("id, name")
    .eq("id", parsed.pharmacyId)
    .single<{ id: number; name: string }>();

  if (pharmacy && parsed.status === "published") {
    await scheduleNotification({
      type: "weekly_general",
      dutyScheduleId: createdDuty.id,
      pharmacyId: pharmacy.id,
      pharmacyName: pharmacy.name,
      startsAt: parsed.startsAt,
      endsAt: parsed.endsAt,
      scheduledFor: parsed.startsAt,
      eventKey: `weekly_general_${createdDuty.id}`
    });

    await scheduleNotification({
      type: "favorite_reminder",
      dutyScheduleId: createdDuty.id,
      pharmacyId: pharmacy.id,
      pharmacyName: pharmacy.name,
      startsAt: parsed.startsAt,
      endsAt: parsed.endsAt,
      scheduledFor: reminderDateForFavoriteStart(new Date(parsed.startsAt)).toISOString(),
      eventKey: `favorite_reminder_${createdDuty.id}`
    });
  }

  revalidatePath("/admin/plantoes");
  revalidatePath("/");
}

export async function generateAutomaticDutyCalendarAction(payload: unknown) {
  const { user } = await requireSuperadmin();
  const parsed = autoGenerateDutySchema.parse(payload);
  const supabase = await createServerSupabaseClient();

  const { data: pharmacies, error: pharmaciesError } = await supabase
    .from("pharmacies")
    .select("id")
    .eq("status", "active")
    .order("rotation_order", { ascending: true });

  if (pharmaciesError || !pharmacies || pharmacies.length === 0) {
    throw new Error("Não foi possível carregar farmácias ativas para rodízio");
  }

  const duties = generateRotationalDuties({
    pharmacyIdsInOrder: pharmacies.map((item: { id: number }) => item.id),
    startWeekDate: new Date(parsed.startWeek),
    weeksCount: parsed.weeksCount,
    status: parsed.status,
    mode: "automatic"
  }).map((duty) => ({
    pharmacy_id: duty.pharmacyId,
    starts_at: duty.startsAt,
    ends_at: duty.endsAt,
    week_start: duty.weekStart,
    week_end: duty.weekEnd,
    mode: duty.mode,
    status: duty.status,
    created_by: user.id
  }));

  const { error: insertError } = await supabase.from("duty_schedules").insert(duties);

  if (insertError) {
    throw new Error(insertError.message);
  }

  revalidatePath("/admin/plantoes");
}
