-- =====================================================
-- Plantão Farmácias GCU - Schema Inicial
-- =====================================================

create extension if not exists pgcrypto;
create extension if not exists btree_gist;

-- =====================================================
-- Enums
-- =====================================================

create type public.user_role as enum ('superadmin', 'pharmacy', 'public');
create type public.status_flag as enum ('active', 'inactive');
create type public.schedule_mode as enum ('manual', 'automatic');
create type public.duty_status as enum ('draft', 'published', 'closed');
create type public.promotion_status as enum ('draft', 'published', 'archived');
create type public.banner_type as enum ('partner', 'ad', 'institutional');
create type public.banner_position as enum ('home_top_secondary', 'home_between_duty_promotions', 'home_footer_partners');
create type public.notification_type as enum ('weekly_general', 'favorite_start', 'favorite_reminder', 'manual_admin');
create type public.notification_channel as enum ('web_push');
create type public.notification_status as enum ('scheduled', 'processing', 'sent', 'failed', 'cancelled');
create type public.delivery_status as enum ('queued', 'sent', 'failed');

-- =====================================================
-- Shared Triggers/Functions
-- =====================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =====================================================
-- Core Tables
-- =====================================================

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  role public.user_role not null default 'public',
  city text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.pharmacies (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  phone text,
  whatsapp text,
  address text not null,
  neighborhood text,
  city text not null,
  logo_url text,
  color_hex text,
  map_url text,
  rotation_order integer not null,
  status public.status_flag not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pharmacies_rotation_order_unique unique (rotation_order),
  constraint pharmacies_color_hex_valid check (
    color_hex is null or color_hex ~* '^#([0-9A-F]{3}|[0-9A-F]{6})$'
  )
);

create index pharmacies_status_idx on public.pharmacies(status);
create index pharmacies_city_idx on public.pharmacies(city);

create table public.pharmacy_users (
  id bigint generated by default as identity primary key,
  pharmacy_id bigint not null references public.pharmacies(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (pharmacy_id, user_id)
);

create index pharmacy_users_user_id_idx on public.pharmacy_users(user_id);

create table public.duty_schedules (
  id bigint generated by default as identity primary key,
  pharmacy_id bigint not null references public.pharmacies(id) on delete restrict,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  week_start date not null,
  week_end date not null,
  mode public.schedule_mode not null,
  status public.duty_status not null default 'draft',
  notes text,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint duty_dates_valid check (ends_at > starts_at),
  constraint duty_week_valid check (week_end >= week_start)
);

-- Impede sobreposição de plantões no período semanal (core rule)
alter table public.duty_schedules
  add constraint duty_schedules_no_overlap
  exclude using gist (
    daterange(week_start, week_end, '[]') with &&
  )
  where (status in ('draft', 'published', 'closed'));

create index duty_schedules_week_idx on public.duty_schedules(week_start, week_end);
create index duty_schedules_pharmacy_idx on public.duty_schedules(pharmacy_id);
create index duty_schedules_status_idx on public.duty_schedules(status);

create table public.promotion_weeks (
  id bigint generated by default as identity primary key,
  pharmacy_id bigint not null references public.pharmacies(id) on delete restrict,
  duty_schedule_id bigint references public.duty_schedules(id) on delete set null,
  week_start date not null,
  week_end date not null,
  status public.promotion_status not null default 'draft',
  archived_at timestamptz,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint promotion_week_dates_valid check (week_end >= week_start),
  constraint promotion_weeks_unique_per_pharmacy_week unique (pharmacy_id, week_start)
);

create index promotion_weeks_status_idx on public.promotion_weeks(status);
create index promotion_weeks_week_idx on public.promotion_weeks(week_start, week_end);

create table public.promotion_products (
  id bigint generated by default as identity primary key,
  promotion_week_id bigint not null references public.promotion_weeks(id) on delete cascade,
  name text not null,
  short_description text,
  image_url text,
  normal_price numeric(12,2) not null,
  promotional_price numeric(12,2) not null,
  is_highlighted boolean not null default false,
  display_order integer not null,
  status public.status_flag not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint promotion_prices_valid check (promotional_price <= normal_price),
  constraint promotion_products_display_order_valid check (display_order >= 1),
  constraint promotion_products_display_order_unique unique (promotion_week_id, display_order)
);

create index promotion_products_week_idx on public.promotion_products(promotion_week_id);
create index promotion_products_status_idx on public.promotion_products(status);

create or replace function public.enforce_product_limit_per_week()
returns trigger
language plpgsql
as $$
declare
  product_count integer;
begin
  if (new.status = 'active') then
    select count(*)
      into product_count
      from public.promotion_products pp
     where pp.promotion_week_id = new.promotion_week_id
       and pp.status = 'active'
       and (tg_op = 'INSERT' or pp.id <> new.id);

    if product_count >= 10 then
      raise exception 'Limite de 10 produtos ativos por semana promocional excedido';
    end if;
  end if;

  return new;
end;
$$;

create trigger trg_enforce_product_limit_per_week
before insert or update on public.promotion_products
for each row
execute function public.enforce_product_limit_per_week();

create table public.banners (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  link_url text,
  position public.banner_position not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  priority integer not null default 0,
  banner_type public.banner_type not null,
  status public.status_flag not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint banner_dates_valid check (ends_at >= starts_at)
);

create index banners_position_status_idx on public.banners(position, status);
create index banners_period_idx on public.banners(starts_at, ends_at);

create table public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  status public.status_flag not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index push_subscriptions_user_idx on public.push_subscriptions(user_id);
create index push_subscriptions_status_idx on public.push_subscriptions(status);

create table public.user_notification_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  receive_general_weekly boolean not null default true,
  receive_favorites boolean not null default true,
  receive_favorite_reminder boolean not null default true,
  reminder_days_before integer not null default 1,
  is_opted_in_push boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reminder_days_before_valid check (reminder_days_before between 0 and 7)
);

create table public.user_favorite_pharmacies (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  pharmacy_id bigint not null references public.pharmacies(id) on delete cascade,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, pharmacy_id)
);

create unique index user_favorite_single_primary_idx
  on public.user_favorite_pharmacies(user_id)
  where is_primary;

create index user_favorite_pharmacy_idx on public.user_favorite_pharmacies(pharmacy_id);

create table public.notifications (
  id bigint generated by default as identity primary key,
  duty_schedule_id bigint references public.duty_schedules(id) on delete set null,
  pharmacy_id bigint references public.pharmacies(id) on delete set null,
  type public.notification_type not null,
  channel public.notification_channel not null default 'web_push',
  title text not null,
  body text not null,
  scheduled_for timestamptz not null,
  event_key text not null,
  status public.notification_status not null default 'scheduled',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (event_key, type, channel)
);

create index notifications_scheduled_idx on public.notifications(status, scheduled_for);
create index notifications_pharmacy_idx on public.notifications(pharmacy_id);

create table public.notification_deliveries (
  id bigint generated by default as identity primary key,
  notification_id bigint not null references public.notifications(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  push_subscription_id bigint references public.push_subscriptions(id) on delete set null,
  status public.delivery_status not null default 'queued',
  provider_response text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique (notification_id, user_id, push_subscription_id)
);

create index notification_deliveries_status_idx on public.notification_deliveries(status);
create index notification_deliveries_user_idx on public.notification_deliveries(user_id);

create table public.settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

-- =====================================================
-- Updated At Triggers
-- =====================================================

create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger trg_pharmacies_updated_at
before update on public.pharmacies
for each row execute function public.set_updated_at();

create trigger trg_duty_schedules_updated_at
before update on public.duty_schedules
for each row execute function public.set_updated_at();

create trigger trg_promotion_weeks_updated_at
before update on public.promotion_weeks
for each row execute function public.set_updated_at();

create trigger trg_promotion_products_updated_at
before update on public.promotion_products
for each row execute function public.set_updated_at();

create trigger trg_banners_updated_at
before update on public.banners
for each row execute function public.set_updated_at();

create trigger trg_push_subscriptions_updated_at
before update on public.push_subscriptions
for each row execute function public.set_updated_at();

create trigger trg_user_notification_preferences_updated_at
before update on public.user_notification_preferences
for each row execute function public.set_updated_at();

create trigger trg_notifications_updated_at
before update on public.notifications
for each row execute function public.set_updated_at();

create trigger trg_settings_updated_at
before update on public.settings
for each row execute function public.set_updated_at();

-- =====================================================
-- Auth Hook: profile bootstrap
-- =====================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce((new.raw_user_meta_data ->> 'role')::public.user_role, 'public'::public.user_role)
  )
  on conflict (id) do nothing;

  insert into public.user_notification_preferences (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- =====================================================
-- Public Views
-- =====================================================

create or replace view public.v_current_duty as
select
  ds.id as duty_id,
  ds.week_start,
  ds.week_end,
  ds.starts_at,
  ds.ends_at,
  p.id as pharmacy_id,
  p.name as pharmacy_name,
  p.slug as pharmacy_slug,
  p.address,
  p.phone,
  p.whatsapp,
  p.map_url
from public.duty_schedules ds
join public.pharmacies p on p.id = ds.pharmacy_id
where ds.status = 'published'
  and current_date between ds.week_start and ds.week_end;

create or replace view public.v_active_banners as
select *
from public.banners
where status = 'active'
  and now() between starts_at and ends_at;

-- =====================================================
-- RLS Helper Functions (dependem das tabelas)
-- =====================================================

create or replace function public.current_user_role()
returns public.user_role
language sql
stable
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), 'public'::public.user_role);
$$;

create or replace function public.is_superadmin()
returns boolean
language sql
stable
as $$
  select public.current_user_role() = 'superadmin'::public.user_role;
$$;

create or replace function public.belongs_to_pharmacy(target_pharmacy_id bigint)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.pharmacy_users pu
    where pu.user_id = auth.uid()
      and pu.pharmacy_id = target_pharmacy_id
  );
$$;

-- =====================================================
-- RLS
-- =====================================================

alter table public.profiles enable row level security;
alter table public.pharmacies enable row level security;
alter table public.pharmacy_users enable row level security;
alter table public.duty_schedules enable row level security;
alter table public.promotion_weeks enable row level security;
alter table public.promotion_products enable row level security;
alter table public.banners enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.user_notification_preferences enable row level security;
alter table public.user_favorite_pharmacies enable row level security;
alter table public.notifications enable row level security;
alter table public.notification_deliveries enable row level security;
alter table public.settings enable row level security;

-- Profiles
create policy "profiles_select_own_or_superadmin"
on public.profiles
for select
using (auth.uid() = id or public.is_superadmin());

create policy "profiles_update_own_or_superadmin"
on public.profiles
for update
using (auth.uid() = id or public.is_superadmin())
with check (auth.uid() = id or public.is_superadmin());

create policy "profiles_insert_self_or_superadmin"
on public.profiles
for insert
with check (auth.uid() = id or public.is_superadmin());

-- Pharmacies
create policy "pharmacies_public_read_active"
on public.pharmacies
for select
using (status = 'active' or public.is_superadmin() or public.belongs_to_pharmacy(id));

create policy "pharmacies_superadmin_manage"
on public.pharmacies
for all
using (public.is_superadmin())
with check (public.is_superadmin());

-- Pharmacy users
create policy "pharmacy_users_superadmin_manage"
on public.pharmacy_users
for all
using (public.is_superadmin())
with check (public.is_superadmin());

create policy "pharmacy_users_user_read_own"
on public.pharmacy_users
for select
using (user_id = auth.uid() or public.is_superadmin());

-- Duty schedules
create policy "duty_schedules_public_read_published"
on public.duty_schedules
for select
using (
  status = 'published'
  or public.is_superadmin()
  or public.belongs_to_pharmacy(pharmacy_id)
);

create policy "duty_schedules_superadmin_manage"
on public.duty_schedules
for all
using (public.is_superadmin())
with check (public.is_superadmin());

-- Promotion weeks
create policy "promotion_weeks_public_read_published"
on public.promotion_weeks
for select
using (
  status = 'published'
  or public.is_superadmin()
  or public.belongs_to_pharmacy(pharmacy_id)
);

create policy "promotion_weeks_superadmin_manage"
on public.promotion_weeks
for all
using (public.is_superadmin())
with check (public.is_superadmin());

-- Promotion products
create policy "promotion_products_public_read"
on public.promotion_products
for select
using (
  status = 'active'
  or public.is_superadmin()
  or exists (
    select 1
    from public.promotion_weeks pw
    where pw.id = promotion_week_id
      and public.belongs_to_pharmacy(pw.pharmacy_id)
  )
);

create policy "promotion_products_superadmin_manage"
on public.promotion_products
for all
using (public.is_superadmin())
with check (public.is_superadmin());

-- Banners
create policy "banners_public_read_active"
on public.banners
for select
using (
  (status = 'active' and now() between starts_at and ends_at)
  or public.is_superadmin()
);

create policy "banners_superadmin_manage"
on public.banners
for all
using (public.is_superadmin())
with check (public.is_superadmin());

-- Push subscriptions
create policy "push_subscriptions_own_or_superadmin"
on public.push_subscriptions
for select
using (user_id = auth.uid() or public.is_superadmin());

create policy "push_subscriptions_insert_own"
on public.push_subscriptions
for insert
with check (user_id = auth.uid() or public.is_superadmin());

create policy "push_subscriptions_update_own"
on public.push_subscriptions
for update
using (user_id = auth.uid() or public.is_superadmin())
with check (user_id = auth.uid() or public.is_superadmin());

create policy "push_subscriptions_delete_own"
on public.push_subscriptions
for delete
using (user_id = auth.uid() or public.is_superadmin());

-- Notification preferences
create policy "notification_preferences_own_or_superadmin"
on public.user_notification_preferences
for select
using (user_id = auth.uid() or public.is_superadmin());

create policy "notification_preferences_insert_own"
on public.user_notification_preferences
for insert
with check (user_id = auth.uid() or public.is_superadmin());

create policy "notification_preferences_update_own"
on public.user_notification_preferences
for update
using (user_id = auth.uid() or public.is_superadmin())
with check (user_id = auth.uid() or public.is_superadmin());

-- Favorites
create policy "favorites_own_or_superadmin"
on public.user_favorite_pharmacies
for select
using (user_id = auth.uid() or public.is_superadmin());

create policy "favorites_insert_own"
on public.user_favorite_pharmacies
for insert
with check (user_id = auth.uid() or public.is_superadmin());

create policy "favorites_update_own"
on public.user_favorite_pharmacies
for update
using (user_id = auth.uid() or public.is_superadmin())
with check (user_id = auth.uid() or public.is_superadmin());

create policy "favorites_delete_own"
on public.user_favorite_pharmacies
for delete
using (user_id = auth.uid() or public.is_superadmin());

-- Notifications (interno)
create policy "notifications_superadmin_manage"
on public.notifications
for all
using (public.is_superadmin())
with check (public.is_superadmin());

-- Deliveries
create policy "notification_deliveries_superadmin_or_owner"
on public.notification_deliveries
for select
using (public.is_superadmin() or user_id = auth.uid());

create policy "notification_deliveries_superadmin_manage"
on public.notification_deliveries
for all
using (public.is_superadmin())
with check (public.is_superadmin());

-- Settings
create policy "settings_superadmin_manage"
on public.settings
for all
using (public.is_superadmin())
with check (public.is_superadmin());
